config/routes.rb
Rails.application.routes.draw do
  # resources :messages
  resources :reviews
  resources :bookings
  # resources :tasker_comments
  resources :taskers
  resources :services
  
  # Devise Gem
  devise_for :users

  # Route to the home action
  get "/home" => "home#home", as: :home

  # Root
  root "home#index"
  
  # Get taskers json
  get '/get_taskers', to: 'services#get_taskers'

  # Privacy policy
  get 'privacy_policy', to: 'home#privacy_policy'

  # Redirect specific routes to HTTPS
  get '/ads.txt', to: redirect(protocol: "https://", status: 301)

  # Not found
  match '*path', to: 'home#not_found', via: :all, constraints: lambda { |req|
    req.path.exclude?('rails/active_storage')
  }

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  get "up" => "rails/health#show", as: :rails_health_check
end

app/models/service.rb
class Service < ApplicationRecord
    # Relationships
    has_and_belongs_to_many :taskers
    has_many :bookings
end

app/controllers/services_controller.rb
class ServicesController < ApplicationController
  before_action :set_service, only: %i[ show edit update destroy ]
  before_action :authenticate_admin!, only: %i[ new edit create update destroy ]

  # GET /services or /services.json
  def index
    @services = Service.all
  end

  # GET /services/1 or /services/1.json
  def show
  end

  # GET /services/new
  def new
    @service = Service.new
  end

  # GET /services/1/edit
  def edit
  end

  # POST /services or /services.json
  def create
    @service = Service.new(service_params)

    respond_to do |format|
      if @service.save
        format.html { redirect_to service_url(@service), notice: "Service was successfully created." }
        format.json { render :show, status: :created, location: @service }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @service.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /services/1 or /services/1.json
  def update
    respond_to do |format|
      if @service.update(service_params)
        format.html { redirect_to service_url(@service), notice: "Service was successfully updated." }
        format.json { render :show, status: :ok, location: @service }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @service.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /services/1 or /services/1.json
  def destroy
    @service.destroy!

    respond_to do |format|
      format.html { redirect_to services_url, notice: "Service was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def get_taskers
    service = Service.find(params[:service_id])
    # service =  Service.find_by(id: 1)
    taskers = service.taskers
    render json: taskers
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_service
      @service = Service.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def service_params
      params.require(:service).permit(:name, :description, :picture)
    end
end

app/helpers/services_helper.rb
module ServicesHelper
end

app/views/services/_form.html.erb
<div class="container mt-5">
  <div class="row">
    <div class="col-6 offset-3">
      <%= form_with(model: service, local: true, class: "form") do |form| %>
        <% if service.errors.any? %>
          <div class="alert alert-danger">
            <h2><%= pluralize(service.errors.count, "error") %> prohibited this service from being saved:</h2>

            <ul>
              <% service.errors.full_messages.each do |error| %>
                <li><%= error %></li>
              <% end %>
            </ul>
          </div>
        <% end %>

        <div class="form-group">
          <%= form.label :name %>
          <%= form.text_field :name, class: "form-control" %>
        </div>

        <div class="form-group">
          <%= form.label :description %>
          <%= form.text_area :description, class: "form-control large-text-area" %>
        </div>

        <div class="form-group mb-3">
          <%= form.label :picture %>
          <%= form.text_field :picture, class: "form-control" %>
        </div>

        <div class="text-center">
          <%= form.submit "Save", class: "btn btn-primary" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/services/_service.html.erb
<div id="<%= dom_id(service) %>" class="container my-4">
  <div class="card text-center">
    <%= image_tag(service.picture , class: "card-img-top service-image-size", alt: "Service Image") %>
    <div class="card-body">
      <h5 class="card-title"><%= service.name %></h5>
      <p class="card-text"><%= service.description %></p>
    </div>
  </div>
</div>

app/views/services/edit.html.erb
<div class="container mt-5">
  <div class="row">
    <div class="col-12 text-center">
      <h1 class="display-4">Editing service</h1>
    </div>
  </div>

  <div class="row">
    <div class="col-6 offset-3">
      <%= render "form", service: @service %>
    </div>
  </div>

  <div class="row">
    <div class="col-12 text-center mt-4">
      <%= link_to "Show this service", @service, class: "btn btn-primary" %>
      <%= link_to "Back to services", services_path, class: "btn btn-secondary" %>
    </div>
  </div>
</div>

app/views/services/index.html.erb
<div class="container mt-5">
  <div class="row">
    <div class="col-12 text-center">
      <h1 class="display-4">Services</h1>
    </div>
  </div>
  <% if user_signed_in? && current_user.email == "cookie@me.con" %>
    <div class="row">
      <div class="col-12 text-center mt-4">
        <%= link_to "New service", new_service_path, class: "btn btn-success" %>
      </div>
    </div>
  <% end %>
  <div class="row">
    <% @services.each do |service| %>
      <div class="col-12 col-md-6 col-lg-4 service-wrapper" data-service-id="<%= service.id %>">
        <%= render service %>
      </div>
    <% end %>
  </div>
</div>
<script>
  document.addEventListener('DOMContentLoaded', function () {
    document.querySelectorAll('.service-wrapper').forEach(function (wrapper) {
      wrapper.addEventListener('click', function () {
        var serviceId = this.getAttribute('data-service-id');
        window.location.href = '/services/' + serviceId;
      });
    });
  });
</script>

app/views/services/new.html.erb
<div class="container mt-5">
  <div class="row">
    <div class="col-12 text-center">
      <h1 class="display-4">New service</h1>
    </div>
  </div>

  <div class="row">
    <div class="col-6 offset-3">
      <%= render "form", service: @service %>
    </div>
  </div>

  <div class="row">
    <div class="col-12 text-center mt-4">
      <%= link_to "Back to services", services_path, class: "btn btn-secondary" %>
    </div>
  </div>
</div>

app/views/services/show.html.erb
<div class="container mt-5">
  <div class="row">
    <div class="col-12">
      <%= link_to services_path, class: "btn btn-dark mb-2" do %>
        <i class="bi bi-arrow-left"></i>
      <% end %>
    </div>
  </div>

  <div class="row">
    <div class="col-12 text-center">
      <p style="color: green"><%= notice %></p>
    </div>
  </div>

  <div class="row">
    <div class="col-12 col-md-6 col-lg-4 show-page">
      <%= render @service %>
    </div>
  </div>

  <div class="row">
    <div class="col-6 offset-3">
      <div class="text-center mt-4">
        <% if user_signed_in? && current_user.email == "cookie@me.con" %>
          <div class="row">
            <div class="col">
              <%= link_to "Edit this service", edit_service_path(@service), class: "btn btn-info mb-2" %>
            </div>
            <div class="col">
              <%= button_to "Destroy this service", @service, method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-danger" %>
            </div>
          </div>
        <% end %> 
      </div>
    </div>
  </div>
</div>

<div class="card my-4 shadow-sm">
  <div class="card-body">
    <h2 class="text-center"> Taskers </h2>
  </div>
</div>

<div class="container my-4">
  <div class="row">
    <% @service.taskers.each do |tasker| %>
      <div class="col-md-4">
        <div id="<%= dom_id(tasker) %>" class="card text-center">
          <% if tasker.image.attached? %>
            <%= image_tag(tasker.image, class: "card-img-top tasker-image-size") %>
          <% else %>
            <img class="card-img-top tasker-image-size" src="<%= tasker.profile_picture %>" alt="Profile picture">
          <% end %>
          <div class="card-body">
            <p class="card-text"><strong>Name:</strong> <%= tasker.name %></p>
            <p class="card-text"><strong>Location:</strong> <%= tasker.location %></p>
            <p class="card-text"><strong>Description:</strong> <%= truncate(tasker.description, length: 100, separator: ' ') %></p>
            <p class="card-text"><strong>Phone number:</strong> <%= tasker.phone_number %></p>
            <%# <p class="card-text"><strong>Rating:</strong> <%= tasker.rating ></p> %>
          </div>
          <div class="card-footer">
            <%= link_to "View profile", tasker_path(tasker), class: "btn btn-primary mx-2" %>
            <%= link_to "Book", new_booking_path(service_id: @service.id, tasker_id: tasker.id), class: "btn btn-primary mx-2" %>
          </div>  
        </div>
      </div>
      <% if (@service.taskers.index(tasker) + 1) % 3 == 0 %>
        </div><div class="row">
      <% end %>
    <% end %>
  </div>
</div>