config/routes.rb
Rails.application.routes.draw do
  # resources :messages
  resources :reviews
  resources :bookings
  # resources :tasker_comments
  resources :taskers
  resources :services
  
  # Devise Gem
  devise_for :users

  # Route to the home action
  get "/home" => "home#home", as: :home

  # Root
  root "home#index"
  
  # Get taskers json
  get '/get_taskers', to: 'services#get_taskers'

  # Privacy policy
  get 'privacy_policy', to: 'home#privacy_policy'

  # Redirect specific routes to HTTPS
  get '/ads.txt', to: redirect(protocol: "https://", status: 301)

  # Not found
  match '*path', to: 'home#not_found', via: :all, constraints: lambda { |req|
    req.path.exclude?('rails/active_storage')
  }

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  get "up" => "rails/health#show", as: :rails_health_check
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def home
  end

  def privacy_policy
  end
end

app/views/home/_navbar.html.erb
<nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">
    <a class="" href="#"><%= link_to raw('TaskBunny <i class="bi bi-arrow-up-short"></i>'), root_path, class: 'logo mx-4' %></a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <li><%= link_to 'Services', services_path, class:"nav-link" %></li>
        </li>
        <li class="nav-item">
          <li><%= link_to 'Taskers', taskers_path, class:"nav-link" %></li>
        </li>
        <li class="nav-item">
          <li><%= link_to 'Booking', bookings_path, class:"nav-link" %></li>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            ...
          </a>
          <ul class="dropdown-menu">
            <li><%= link_to 'Reviews', reviews_path, class:"dropdown-item" %></li>
            <li><%= link_to 'Store', root_path, class:"dropdown-item" %></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="/privacy_policy">Privacy Policy</a></li>
          </ul>
        </li>
        <% if user_signed_in? %>
          <li><%= button_to "Log Out", destroy_user_session_path, method: :delete, class: "btn btn-dark mx-3" %></li>
        <% else %>
          <li><%= link_to 'Sign up', new_user_registration_path, class: "nav-link text-primary mx-2" %></li>
          <li><%= link_to 'Sign in', new_user_session_path, class: "nav-link text-primary mx-2" %></li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>