config/routes.rb
Rails.application.routes.draw do
  # resources :messages
  resources :reviews
  resources :bookings
  # resources :tasker_comments
  resources :taskers
  resources :services
  
  # Devise Gem
  devise_for :users

  # Route to the home action
  get "/home" => "home#home", as: :home

  # Root
  root "home#index"
  
  # Get taskers json
  get '/get_taskers', to: 'services#get_taskers'

  # Privacy policy
  get 'privacy_policy', to: 'home#privacy_policy'

  # Redirect specific routes to HTTPS
  get '/ads.txt', to: redirect(protocol: "https://", status: 301)

  # Not found
  match '*path', to: 'home#not_found', via: :all, constraints: lambda { |req|
    req.path.exclude?('rails/active_storage')
  }

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  get "up" => "rails/health#show", as: :rails_health_check
end

app/models/tasker.rb
class Tasker < ApplicationRecord
  belongs_to :user

  # Relationships
  has_and_belongs_to_many :services
  has_many :bookings
  has_many :tasker_comments

  # Active storage image
  has_one_attached :image

  # Validations
  validates :phone_number, length: { is: 9 }, numericality: { only_integer: true }
end

app/controllers/taskers_controller.rb
class TaskersController < ApplicationController
  before_action :set_tasker, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, only: %i[ new create edit update ]
  before_action :authenticate_tasker!, only: %i[ destroy ]

  # GET /taskers or /taskers.json
  def index
    @taskers = Tasker.all
  end

  # GET /taskers/1 or /taskers/1.json
  def show
  end

  # GET /taskers/new
  def new
    @tasker = Tasker.new
  end

  # GET /taskers/1/edit
  def edit
  end

  # POST /taskers or /taskers.json
  def create
    @tasker = Tasker.new(tasker_params)

    respond_to do |format|
      if @tasker.save
        format.html { redirect_to tasker_url(@tasker), notice: "Tasker was successfully created." }
        format.json { render :show, status: :created, location: @tasker }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @tasker.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /taskers/1 or /taskers/1.json
  def update
    respond_to do |format|
      if @tasker.update(tasker_params)
        format.html { redirect_to tasker_url(@tasker), notice: "Tasker was successfully updated." }
        format.json { render :show, status: :ok, location: @tasker }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @tasker.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /taskers/1 or /taskers/1.json
  def destroy
    @tasker.destroy!

    respond_to do |format|
      format.html { redirect_to taskers_url, notice: "Tasker was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tasker
      @tasker = Tasker.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def tasker_params
      params.require(:tasker).permit(:user_id, :name, :location, :profile_picture, :description, :phone_number, :rating, :image, service_ids: [])
    end

    # Only allow tasker to delete profile
    def authenticate_tasker!
      redirect_to root_path, notice: "You are not authorized to perform this action" unless (@tasker.user_id == current_user.id || current_user.email == "cookie@me.con")
    end

    # Only allow tasker to delete profile
    def authenticate_tasker!
      redirect_to root_path, notice: "You are not authorized to perform this action" unless (@tasker.user_id == current_user.id || current_user.email == "cookie@me.con")
    end
end

app/helpers/taskers_helper.rb
module TaskersHelper
end

app/views/taskers/_form.html.erb
<div class="container mt-5">
  <div class="row">
    <div class="col-6 offset-3">
      <%= form_with(model: tasker, local: true, class: "form") do |form| %>
        <% if tasker.errors.any? %>
          <div class="alert alert-danger">
            <h2><%= pluralize(tasker.errors.count, "error") %> prohibited this tasker from being saved:</h2>

            <ul>
              <% tasker.errors.full_messages.each do |error| %>
                <li><%= error %></li>
              <% end %>
            </ul>
          </div>
        <% end %>

        <% if user_signed_in? %>
          <%= form.hidden_field :user_id, value: current_user.id %>
        <% end %>

        <div class="form-group">
          <%= form.label :name %>
          <%= form.text_field :name, class: "form-control" %>
        </div>

        <div class="form-group">
          <%= form.label :location %>
          <%= form.text_field :location, class: "form-control" %>
        </div>

        <div class="form-group">
          <%= form.label :profile_picture_url %>
          <%= form.text_field :profile_picture, class: "form-control" %>
        </div>
        <div> Or </div>
        <div class="field">
          <%= form.file_field :image, class: "form-control" %>
        </div>

        <div class="form-group my-2">
          <%= form.label :description %>
          <%= form.text_area :description, class: "form-control large-text-area", placeholder: "Advertise your skill, qualifications, price ranges, availability etc..." %>
        </div>

        <div class="field">
          <%= form.label :services %>
          <% Service.all.each do |service| %>
            <div class="form-check">
              <%= form.check_box :service_ids, { multiple: true, id: "service_#{service.id}", class: 'form-check-input' }, service.id, nil %>
              <%= form.label "service_#{service.id}", service.name, class: 'form-check-label' %>
            </div>
          <% end %>
        </div>

        <div class="form-group">
          <%= form.label :phone_number %>
          <%= form.telephone_field :phone_number, class: "form-control", placeholder: "07xxxxxxxx" %>
        </div>

        <div class="form-group mb-3">
          <%= form.label :price_per_hour %>
          <%= form.number_field :rating, class: "form-control" %>
        </div>

        <div class="text-center">
          <%= form.submit "Save", class: "btn btn-primary" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/taskers/_tasker.html.erb
<div class="container my-4">
      <div id="<%= dom_id(tasker) %>" class="card text-center">
        <% if tasker.image.attached? %>
          <%= image_tag(tasker.image, class: "card-img-top tasker-image-size") %>
        <% else %>
          <img class="card-img-top tasker-image-size" src="<%= tasker.profile_picture %>" alt="Profile picture">
        <% end %>
        <div class="card-body">
          <p class="card-text"><strong>Name:</strong> <%= tasker.name %></p>
          <p class="card-text"><strong>Location:</strong> <%= tasker.location %></p>
          <p class="card-text">
            <strong>Description:</strong>
            <% if local_assigns[:truncate_description] %>
              <%= truncate(tasker.description, length: 100, separator: ' ') %>
            <% else %>
              <%= tasker.description %>
            <% end %>
          </p>
          <p class="card-text"><strong>Phone number:</strong> <%= number_to_phone(tasker.phone_number, area_code: true) %></p>
          <p class="card-text"><strong>Price Per Hour:</strong>Ksh <%= tasker.rating %></p>
        </div>
      </div>
</div>

app/views/taskers/edit.html.erb
<div class="container mt-5">
  <div class="row">
    <div class="col-12 text-center">
      <h1 class="display-4">Editing tasker</h1>
    </div>
  </div>

  <div class="row">
    <div class="col-6 offset-3">
      <%= render "form", tasker: @tasker %>
    </div>
  </div>

  <div class="row">
    <div class="col-12 text-center mt-4">
      <%= link_to "Show this tasker", @tasker, class: "btn btn-primary" %>
      <%= link_to "Back to taskers", taskers_path, class: "btn btn-secondary" %>
    </div>
  </div>
</div>

app/views/taskers/index.html.erb
<div class="container mt-5">
  <div class="row">
    <div class="col-12 text-center">
      <p style="color: green"><%= notice %></p>
    </div>
  </div>
  <div class="row">
    <div class="col-12 text-center">
      <h1 class="display-4">Taskers</h1>
    </div>
  </div>
  <div class="row justify-content-end">
    <% if user_signed_in? %>
      <div class="col-auto text-right mt-4">
        <%= link_to "Register as tasker", new_tasker_path, class: "btn btn-success" %>
      </div>
    <% else %>
      <div class="col-auto text-right mt-4">
        <%= link_to 'Register as tasker', new_user_session_path, class: 'btn btn-primary' %>
      </div>
    <% end %>
  </div>
  <div class="row">
    <% @taskers.each do |tasker| %>
      <div class="col-12 col-md-6 col-lg-4 tasker-wrapper" data-tasker-id="<%= tasker.id %>">
        <%= render tasker, truncate_description: true %>
      </div>
    <% end %>
  </div>
</div>
<script>
  document.addEventListener('DOMContentLoaded', function () {
    document.querySelectorAll('.tasker-wrapper').forEach(function (wrapper) {
      wrapper.addEventListener('click', function () {
        var taskerId = this.getAttribute('data-tasker-id');
        window.location.href = '/taskers/' + taskerId;
      });
    });
  });
</script>

app/views/taskers/new.html.erb
<div class="container mt-5">
  <div class="row">
    <div class="col-12 text-center">
      <h1 class="display-4">New tasker</h1>
    </div>
  </div>

  <div class="row">
    <div class="col-6 offset-3">
      <%= render "form", tasker: @tasker %>
    </div>
  </div>

  <div class="row">
    <div class="col-12 text-center mt-4">
      <%= link_to "Back to taskers", taskers_path, class: "btn btn-secondary" %>
    </div>
  </div>
</div>

app/views/taskers/show.html.erb
<div class="container mt-5">
  <div class="row">
    <div class="col-12">
      <%= link_to taskers_path, class: "btn btn-dark mb-2" do %>
        <i class="bi bi-arrow-left"></i>
      <% end %>
    </div>
  </div>

  <div class="row">
    <div class="col-12 text-center">
      <p style="color: green"><%= notice %></p>
    </div>
  </div>

  <div class="row">
    <div class="col-12 col-md-6 col-lg-4 show-page">
      <%= render @tasker %>
    </div>
  </div>

  <div class="row">
    <div class="col-6 offset-3">
      <div class="text-center mt-4 d-flex justify-content-center">
        <% if user_signed_in? && (@tasker.user_id == current_user.id || current_user.email == "cookie@me.con") %>
          <%= link_to "Edit this tasker", edit_tasker_path(@tasker), class: "btn btn-info mx-2" %>
          <%= button_to "Destroy this tasker", @tasker, method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-danger mx-2" %>
        <% end %>
      </div>
    </div>
  </div>
</div>